# Panda Live Demo Step

Notebook version of `panda_live_demo_step.py` with one step per cell.

In [1]:
from pathlib import Path

import pandas as pd
from IPython.display import display

# Notebook lives in labs/ITSE-1003/pandas/, so data/ is one level up.
data_dir = Path.cwd().parent / "data"

# step 1: load student rows from CSV
df = pd.read_csv(data_dir / "students.csv")
df.columns = df.columns.str.strip()

In [3]:
# step 2: print the full DataFrame
display(df)

,Id,Name,Age,Major,GPA,Email,City,Phone,Birth_Date,grade,grade_letter
0,1,Alice Johnson,35,Computer Science,3.5,alice@email.com,New York,555-0101,1990-05-15,90,A
1,2,Bob Smith,28,Mathematics,3.8,bob@email.com,Los Angeles,555-0202,1985-12-25,85,B
2,3,Charlie Brown,42,Physics,4.0,charlie@email.com,Chicago,555-0303,2000-02-29,100,C
3,4,Diana Prince,31,Chemistry,3.2,diana@email.com,Houston,555-0404,1992-08-30,92,D
4,5,Eve Wilson,45,Biology,3.5,eve@email.com,Phoenix,555-0505,1975-11-12,75,E
5,6,Frank Miller,29,Economics,3.8,frank@email.com,Boston,555-0606,1994-07-18,94,F
6,7,Grace Lee,38,English,3.5,grace@email.com,Seattle,555-0707,1983-03-22,83,G
7,8,Henry Davis,51,History,3.8,henry@email.com,Miami,555-0808,1970-09-05,70,H
8,9,Iris Chen,26,Art,3.2,iris@email.com,Denver,555-0909,1996-04-14,96,I
9,10,Kevin Ortiz,22,Computer Science,2.1,kevin.ortiz@email.com,Austin,555-1010,2002-01-10,55,F
10,11,Mia Wong,20,Mathematics,2.4,mia.wong@email.com,Portland,555-1111,2004-06-20,62,D
11,12,Leo King,24,Physics,2.0,leo.king@email.com,Dallas,555-1212,2000-11-05,68,D
12,13,Nora Ali,19,Chemistry,1.9,nora.ali@email.com,Tampa,555-1313,2005-03-18,45,F

In [4]:
# step 3: show first 5 rows
display(df.head())

,Id,Name,Age,Major,GPA,Email,City,Phone,Birth_Date,grade,grade_letter
0,1,Alice Johnson,35,Computer Science,3.5,alice@email.com,New York,555-0101,1990-05-15,90,A
1,2,Bob Smith,28,Mathematics,3.8,bob@email.com,Los Angeles,555-0202,1985-12-25,85,B
2,3,Charlie Brown,42,Physics,4.0,charlie@email.com,Chicago,555-0303,2000-02-29,100,C
3,4,Diana Prince,31,Chemistry,3.2,diana@email.com,Houston,555-0404,1992-08-30,92,D
4,5,Eve Wilson,45,Biology,3.5,eve@email.com,Phoenix,555-0505,1975-11-12,75,E

In [5]:
# step 4: show last 5 rows
display(df.tail())

,Id,Name,Age,Major,GPA,Email,City,Phone,Birth_Date,grade,grade_letter
8,9,Iris Chen,26,Art,3.2,iris@email.com,Denver,555-0909,1996-04-14,96,I
9,10,Kevin Ortiz,22,Computer Science,2.1,kevin.ortiz@email.com,Austin,555-1010,2002-01-10,55,F
10,11,Mia Wong,20,Mathematics,2.4,mia.wong@email.com,Portland,555-1111,2004-06-20,62,D
11,12,Leo King,24,Physics,2.0,leo.king@email.com,Dallas,555-1212,2000-11-05,68,D
12,13,Nora Ali,19,Chemistry,1.9,nora.ali@email.com,Tampa,555-1313,2005-03-18,45,F

In [6]:
# step 5: show DataFrame info
print("\nInfo:")
df.info()

Info:
<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            13 non-null     int64
 1   Name          13 non-null     str
 2   Age           13 non-null     int64
 3   Major         13 non-null     str
 4   GPA           13 non-null     float64
 5   Email         13 non-null     str
 6   City          13 non-null     str
 7   Phone         13 non-null     str
 8   Birth_Date    13 non-null     str
 9   grade         13 non-null     int64
 10  grade_letter  13 non-null     str
dtypes: float64(1), int64(3), str(7)
memory usage: 1.2 KB

In [7]:
# step 6: show numeric summary statistics
display(df.describe())

             Id        Age        GPA       grade
count  13.00000  13.000000  13.000000   13.000000
mean    7.00000  31.538462   3.130769   78.076923
std     3.89444  10.046686   0.758710   17.138949
min     1.00000  19.000000   1.900000   45.000000
25%     4.00000  24.000000   2.400000   68.000000
50%     7.00000  29.000000   3.500000   83.000000
75%    10.00000  38.000000   3.800000   92.000000
max    13.00000  51.000000   4.000000  100.000000

In [8]:
# step 7: show column names
display(df.columns)

Index(['Id', 'Name', 'Age', 'Major', 'GPA', 'Email', 'City', 'Phone',
       'Birth_Date', 'grade', 'grade_letter'],
      dtype='str')

In [9]:
# step 8: select one column
display(df["Name"])

0     Alice Johnson
1         Bob Smith
2     Charlie Brown
3      Diana Prince
4        Eve Wilson
5      Frank Miller
6         Grace Lee
7       Henry Davis
8         Iris Chen
9       Kevin Ortiz
10         Mia Wong
11         Leo King
12         Nora Ali
Name: Name, dtype: str

In [10]:
# step 9: select multiple columns
display(df[["Name", "Age", "Major"]])

             Name  Age             Major
0   Alice Johnson   35  Computer Science
1       Bob Smith   28       Mathematics
2   Charlie Brown   42           Physics
3    Diana Prince   31         Chemistry
4      Eve Wilson   45           Biology
5    Frank Miller   29         Economics
6       Grace Lee   38           English
7     Henry Davis   51           History
8       Iris Chen   26               Art
9     Kevin Ortiz   22  Computer Science
10       Mia Wong   20       Mathematics
11       Leo King   24           Physics
12       Nora Ali   19         Chemistry

In [11]:
# step 10: select rows using loc
display(df.loc[df["Age"] > 30])

,Id,Name,Age,Major,GPA,Email,City,Phone,Birth_Date,grade,grade_letter
0,1,Alice Johnson,35,Computer Science,3.5,alice@email.com,New York,555-0101,1990-05-15,90,A
2,3,Charlie Brown,42,Physics,4.0,charlie@email.com,Chicago,555-0303,2000-02-29,100,C
3,4,Diana Prince,31,Chemistry,3.2,diana@email.com,Houston,555-0404,1992-08-30,92,D
4,5,Eve Wilson,45,Biology,3.5,eve@email.com,Phoenix,555-0505,1975-11-12,75,E
6,7,Grace Lee,38,English,3.5,grace@email.com,Seattle,555-0707,1983-03-22,83,G
7,8,Henry Davis,51,History,3.8,henry@email.com,Miami,555-0808,1970-09-05,70,H

In [12]:
# step 11: select rows using slice
display(df[0:3])

,Id,Name,Age,Major,GPA,Email,City,Phone,Birth_Date,grade,grade_letter
0,1,Alice Johnson,35,Computer Science,3.5,alice@email.com,New York,555-0101,1990-05-15,90,A
1,2,Bob Smith,28,Mathematics,3.8,bob@email.com,Los Angeles,555-0202,1985-12-25,85,B
2,3,Charlie Brown,42,Physics,4.0,charlie@email.com,Chicago,555-0303,2000-02-29,100,C

In [13]:
# step 12: select one row using iloc
display(df.iloc[0])

Id                             1
Name               Alice Johnson
Age                           35
Major           Computer Science
GPA                          3.5
Email            alice@email.com
City                    New York
Phone                   555-0101
Birth_Date            1990-05-15
grade                         90
grade_letter                   A
Name: 0, dtype: object

In [14]:
# step 13: filter Age > 30
display(df[df["Age"] > 30])

,Id,Name,Age,Major,GPA,Email,City,Phone,Birth_Date,grade,grade_letter
0,1,Alice Johnson,35,Computer Science,3.5,alice@email.com,New York,555-0101,1990-05-15,90,A
2,3,Charlie Brown,42,Physics,4.0,charlie@email.com,Chicago,555-0303,2000-02-29,100,C
3,4,Diana Prince,31,Chemistry,3.2,diana@email.com,Houston,555-0404,1992-08-30,92,D
4,5,Eve Wilson,45,Biology,3.5,eve@email.com,Phoenix,555-0505,1975-11-12,75,E
6,7,Grace Lee,38,English,3.5,grace@email.com,Seattle,555-0707,1983-03-22,83,G
7,8,Henry Davis,51,History,3.8,henry@email.com,Miami,555-0808,1970-09-05,70,H

In [15]:
# step 14: filter Age > 20 using loc
display(df.loc[df["Age"] > 20])

,Id,Name,Age,Major,GPA,Email,City,Phone,Birth_Date,grade,grade_letter
0,1,Alice Johnson,35,Computer Science,3.5,alice@email.com,New York,555-0101,1990-05-15,90,A
1,2,Bob Smith,28,Mathematics,3.8,bob@email.com,Los Angeles,555-0202,1985-12-25,85,B
2,3,Charlie Brown,42,Physics,4.0,charlie@email.com,Chicago,555-0303,2000-02-29,100,C
3,4,Diana Prince,31,Chemistry,3.2,diana@email.com,Houston,555-0404,1992-08-30,92,D
4,5,Eve Wilson,45,Biology,3.5,eve@email.com,Phoenix,555-0505,1975-11-12,75,E
5,6,Frank Miller,29,Economics,3.8,frank@email.com,Boston,555-0606,1994-07-18,94,F
6,7,Grace Lee,38,English,3.5,grace@email.com,Seattle,555-0707,1983-03-22,83,G
7,8,Henry Davis,51,History,3.8,henry@email.com,Miami,555-0808,1970-09-05,70,H
8,9,Iris Chen,26,Art,3.2,iris@email.com,Denver,555-0909,1996-04-14,96,I
9,10,Kevin Ortiz,22,Computer Science,2.1,kevin.ortiz@email.com,Austin,555-1010,2002-01-10,55,F
11,12,Leo King,24,Physics,2.0,leo.king@email.com,Dallas,555-1212,2000-11-05,68,D

In [16]:
# step 15: same filter using iloc
display(df.iloc[(df["Age"] > 20).to_numpy().nonzero()[0]])

,Id,Name,Age,Major,GPA,Email,City,Phone,Birth_Date,grade,grade_letter
0,1,Alice Johnson,35,Computer Science,3.5,alice@email.com,New York,555-0101,1990-05-15,90,A
1,2,Bob Smith,28,Mathematics,3.8,bob@email.com,Los Angeles,555-0202,1985-12-25,85,B
2,3,Charlie Brown,42,Physics,4.0,charlie@email.com,Chicago,555-0303,2000-02-29,100,C
3,4,Diana Prince,31,Chemistry,3.2,diana@email.com,Houston,555-0404,1992-08-30,92,D
4,5,Eve Wilson,45,Biology,3.5,eve@email.com,Phoenix,555-0505,1975-11-12,75,E
5,6,Frank Miller,29,Economics,3.8,frank@email.com,Boston,555-0606,1994-07-18,94,F
6,7,Grace Lee,38,English,3.5,grace@email.com,Seattle,555-0707,1983-03-22,83,G
7,8,Henry Davis,51,History,3.8,henry@email.com,Miami,555-0808,1970-09-05,70,H
8,9,Iris Chen,26,Art,3.2,iris@email.com,Denver,555-0909,1996-04-14,96,I
9,10,Kevin Ortiz,22,Computer Science,2.1,kevin.ortiz@email.com,Austin,555-1010,2002-01-10,55,F
11,12,Leo King,24,Physics,2.0,leo.king@email.com,Dallas,555-1212,2000-11-05,68,D

In [17]:
# step 16: first three rows again
display(df[0:3])

,Id,Name,Age,Major,GPA,Email,City,Phone,Birth_Date,grade,grade_letter
0,1,Alice Johnson,35,Computer Science,3.5,alice@email.com,New York,555-0101,1990-05-15,90,A
1,2,Bob Smith,28,Mathematics,3.8,bob@email.com,Los Angeles,555-0202,1985-12-25,85,B
2,3,Charlie Brown,42,Physics,4.0,charlie@email.com,Chicago,555-0303,2000-02-29,100,C

In [18]:
# step 17: grade letter A
display(df.loc[df["grade_letter"].str.strip() == "A"])

,Id,Name,Age,Major,GPA,Email,City,Phone,Birth_Date,grade,grade_letter
0,1,Alice Johnson,35,Computer Science,3.5,alice@email.com,New York,555-0101,1990-05-15,90,A

In [19]:
# step 18: grade > 70
display(df.loc[df["grade"] > 70])

,Id,Name,Age,Major,GPA,Email,City,Phone,Birth_Date,grade,grade_letter
0,1,Alice Johnson,35,Computer Science,3.5,alice@email.com,New York,555-0101,1990-05-15,90,A
1,2,Bob Smith,28,Mathematics,3.8,bob@email.com,Los Angeles,555-0202,1985-12-25,85,B
2,3,Charlie Brown,42,Physics,4.0,charlie@email.com,Chicago,555-0303,2000-02-29,100,C
3,4,Diana Prince,31,Chemistry,3.2,diana@email.com,Houston,555-0404,1992-08-30,92,D
4,5,Eve Wilson,45,Biology,3.5,eve@email.com,Phoenix,555-0505,1975-11-12,75,E
5,6,Frank Miller,29,Economics,3.8,frank@email.com,Boston,555-0606,1994-07-18,94,F
6,7,Grace Lee,38,English,3.5,grace@email.com,Seattle,555-0707,1983-03-22,83,G
8,9,Iris Chen,26,Art,3.2,iris@email.com,Denver,555-0909,1996-04-14,96,I

In [20]:
# step 19: add Passed column
df["Passed"] = df["grade"] >= 70
display(df)

,Id,Name,Age,Major,GPA,Email,City,Phone,Birth_Date,grade,grade_letter,Passed
0,1,Alice Johnson,35,Computer Science,3.5,alice@email.com,New York,555-0101,1990-05-15,90,A,True
1,2,Bob Smith,28,Mathematics,3.8,bob@email.com,Los Angeles,555-0202,1985-12-25,85,B,True
2,3,Charlie Brown,42,Physics,4.0,charlie@email.com,Chicago,555-0303,2000-02-29,100,C,True
3,4,Diana Prince,31,Chemistry,3.2,diana@email.com,Houston,555-0404,1992-08-30,92,D,True
4,5,Eve Wilson,45,Biology,3.5,eve@email.com,Phoenix,555-0505,1975-11-12,75,E,True
5,6,Frank Miller,29,Economics,3.8,frank@email.com,Boston,555-0606,1994-07-18,94,F,True
6,7,Grace Lee,38,English,3.5,grace@email.com,Seattle,555-0707,1983-03-22,83,G,True
7,8,Henry Davis,51,History,3.8,henry@email.com,Miami,555-0808,1970-09-05,70,H,True
8,9,Iris Chen,26,Art,3.2,iris@email.com,Denver,555-0909,1996-04-14,96,I,True
9,10,Kevin Ortiz,22,Computer Science,2.1,kevin.ortiz@email.com,Austin,555-1010,2002-01-10,55,F,False
10,11,Mia Wong,20,Mathematics,2.4,mia.wong@email.com,Portland,555-1111,2004-06-20,62,D,False
11,12,Leo King,24,Physics,2.0,leo.king@email.com,Dallas,555-1212,2000-11-05,68,D,False
12,13,Nora Ali,19,Chemistry,1.9,nora.ali@email.com,Tampa,555-1313,2005-03-18,45,F,False

In [21]:
# step 20: add Status column
df["Status"] = df["grade"].apply(lambda x: "Passed" if x >= 70 else "Failed")
display(df)

,Id,Name,Age,Major,GPA,Email,City,Phone,Birth_Date,grade,grade_letter,Passed,Status
0,1,Alice Johnson,35,Computer Science,3.5,alice@email.com,New York,555-0101,1990-05-15,90,A,True,Passed
1,2,Bob Smith,28,Mathematics,3.8,bob@email.com,Los Angeles,555-0202,1985-12-25,85,B,True,Passed
2,3,Charlie Brown,42,Physics,4.0,charlie@email.com,Chicago,555-0303,2000-02-29,100,C,True,Passed
3,4,Diana Prince,31,Chemistry,3.2,diana@email.com,Houston,555-0404,1992-08-30,92,D,True,Passed
4,5,Eve Wilson,45,Biology,3.5,eve@email.com,Phoenix,555-0505,1975-11-12,75,E,True,Passed
5,6,Frank Miller,29,Economics,3.8,frank@email.com,Boston,555-0606,1994-07-18,94,F,True,Passed
6,7,Grace Lee,38,English,3.5,grace@email.com,Seattle,555-0707,1983-03-22,83,G,True,Passed
7,8,Henry Davis,51,History,3.8,henry@email.com,Miami,555-0808,1970-09-05,70,H,True,Passed
8,9,Iris Chen,26,Art,3.2,iris@email.com,Denver,555-0909,1996-04-14,96,I,True,Passed
9,10,Kevin Ortiz,22,Computer Science,2.1,kevin.ortiz@email.com,Austin,555-1010,2002-01-10,55,F,False,Failed
10,11,Mia Wong,20,Mathematics,2.4,mia.wong@email.com,Portland,555-1111,2004-06-20,62,D,False,Failed
11,12,Leo King,24,Physics,2.0,leo.king@email.com,Dallas,555-1212,2000-11-05,68,D,False,Failed
12,13,Nora Ali,19,Chemistry,1.9,nora.ali@email.com,Tampa,555-1313,2005-03-18,45,F,False,Failed

In [22]:
# step 21: sort by Age descending
display(df.sort_values(by="Age", ascending=False))

,Id,Name,Age,Major,GPA,Email,City,Phone,Birth_Date,grade,grade_letter,Passed,Status
7,8,Henry Davis,51,History,3.8,henry@email.com,Miami,555-0808,1970-09-05,70,H,True,Passed
4,5,Eve Wilson,45,Biology,3.5,eve@email.com,Phoenix,555-0505,1975-11-12,75,E,True,Passed
2,3,Charlie Brown,42,Physics,4.0,charlie@email.com,Chicago,555-0303,2000-02-29,100,C,True,Passed
6,7,Grace Lee,38,English,3.5,grace@email.com,Seattle,555-0707,1983-03-22,83,G,True,Passed
0,1,Alice Johnson,35,Computer Science,3.5,alice@email.com,New York,555-0101,1990-05-15,90,A,True,Passed
3,4,Diana Prince,31,Chemistry,3.2,diana@email.com,Houston,555-0404,1992-08-30,92,D,True,Passed
5,6,Frank Miller,29,Economics,3.8,frank@email.com,Boston,555-0606,1994-07-18,94,F,True,Passed
1,2,Bob Smith,28,Mathematics,3.8,bob@email.com,Los Angeles,555-0202,1985-12-25,85,B,True,Passed
8,9,Iris Chen,26,Art,3.2,iris@email.com,Denver,555-0909,1996-04-14,96,I,True,Passed
11,12,Leo King,24,Physics,2.0,leo.king@email.com,Dallas,555-1212,2000-11-05,68,D,False,Failed
9,10,Kevin Ortiz,22,Computer Science,2.1,kevin.ortiz@email.com,Austin,555-1010,2002-01-10,55,F,False,Failed
10,11,Mia Wong,20,Mathematics,2.4,mia.wong@email.com,Portland,555-1111,2004-06-20,62,D,False,Failed
12,13,Nora Ali,19,Chemistry,1.9,nora.ali@email.com,Tampa,555-1313,2005-03-18,45,F,False,Failed

In [23]:
# step 22: sort by Age ascending
display(df.sort_values(by="Age", ascending=True))

,Id,Name,Age,Major,GPA,Email,City,Phone,Birth_Date,grade,grade_letter,Passed,Status
12,13,Nora Ali,19,Chemistry,1.9,nora.ali@email.com,Tampa,555-1313,2005-03-18,45,F,False,Failed
10,11,Mia Wong,20,Mathematics,2.4,mia.wong@email.com,Portland,555-1111,2004-06-20,62,D,False,Failed
9,10,Kevin Ortiz,22,Computer Science,2.1,kevin.ortiz@email.com,Austin,555-1010,2002-01-10,55,F,False,Failed
11,12,Leo King,24,Physics,2.0,leo.king@email.com,Dallas,555-1212,2000-11-05,68,D,False,Failed
8,9,Iris Chen,26,Art,3.2,iris@email.com,Denver,555-0909,1996-04-14,96,I,True,Passed
1,2,Bob Smith,28,Mathematics,3.8,bob@email.com,Los Angeles,555-0202,1985-12-25,85,B,True,Passed
5,6,Frank Miller,29,Economics,3.8,frank@email.com,Boston,555-0606,1994-07-18,94,F,True,Passed
3,4,Diana Prince,31,Chemistry,3.2,diana@email.com,Houston,555-0404,1992-08-30,92,D,True,Passed
0,1,Alice Johnson,35,Computer Science,3.5,alice@email.com,New York,555-0101,1990-05-15,90,A,True,Passed
6,7,Grace Lee,38,English,3.5,grace@email.com,Seattle,555-0707,1983-03-22,83,G,True,Passed
2,3,Charlie Brown,42,Physics,4.0,charlie@email.com,Chicago,555-0303,2000-02-29,100,C,True,Passed
4,5,Eve Wilson,45,Biology,3.5,eve@email.com,Phoenix,555-0505,1975-11-12,75,E,True,Passed
7,8,Henry Davis,51,History,3.8,henry@email.com,Miami,555-0808,1970-09-05,70,H,True,Passed

In [24]:
# step 23: group by Major and count rows
display(df.groupby("Major").size())

Major
Art                 1
Biology             1
Chemistry           2
Computer Science    2
Economics           1
English             1
History             1
Mathematics         2
Physics             2
dtype: int64

In [25]:
# step 24: average grade per major
display(df.groupby("Major")["grade"].mean())

Major
Art                 96.0
Biology             75.0
Chemistry           68.5
Computer Science    72.5
Economics           94.0
English             83.0
History             70.0
Mathematics         73.5
Physics             84.0
Name: grade, dtype: float64

In [26]:
# step 25: highest grade
display(df[df["grade"] == df["grade"].max()])

,Id,Name,Age,Major,GPA,Email,City,Phone,Birth_Date,grade,grade_letter,Passed,Status
2,3,Charlie Brown,42,Physics,4.0,charlie@email.com,Chicago,555-0303,2000-02-29,100,C,True,Passed

In [27]:
# step 26: lowest grade
display(df[df["grade"] == df["grade"].min()])

,Id,Name,Age,Major,GPA,Email,City,Phone,Birth_Date,grade,grade_letter,Passed,Status
12,13,Nora Ali,19,Chemistry,1.9,nora.ali@email.com,Tampa,555-1313,2005-03-18,45,F,False,Failed

In [28]:
# step 27: highest GPA
display(df[df["GPA"] == df["GPA"].max()])

,Id,Name,Age,Major,GPA,Email,City,Phone,Birth_Date,grade,grade_letter,Passed,Status
2,3,Charlie Brown,42,Physics,4.0,charlie@email.com,Chicago,555-0303,2000-02-29,100,C,True,Passed

In [29]:
# step 28: combined conditions
display(df[(df["Age"] > 30) & (df["Major"] == "Computer Science")])

,Id,Name,Age,Major,GPA,Email,City,Phone,Birth_Date,grade,grade_letter,Passed,Status
0,1,Alice Johnson,35,Computer Science,3.5,alice@email.com,New York,555-0101,1990-05-15,90,A,True,Passed

In [30]:
# step 29: save updated CSV
print("\nSave the updated DataFrame to a new CSV file:")
df.to_csv(data_dir / "students_updated.csv", index=False)

Save the updated DataFrame to a new CSV file: